services:
  frontend:
    build:
      context: ./challenge-gotam-front
    ports:
      - "4200:80"
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build:
      context: ./challenge-gotam-server
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - DATABASE_PASSWORD=rootpassword
      - DATABASE_NAME=mydb
      - DATABASE_SYNCHRONIZE=true
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
